# Generated by Django 4.2.2 on 2023-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobileid', models.IntegerField()),
                ('Mobilebrand', models.CharField(max_length=100)),
                ('Mobilemodel', models.CharField(max_length=100)),
                ('Mobilecolor', models.CharField(max_length=100)),
                ('Specifications', models.TextField()),
                ('Mobileprice', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
