# Generated by Django 4.2.2 on 2023-07-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gadget',
            new_name='mobiles',
        ),
    ]
